blog_app:
    class: Statocles::App::Blog
    args:
        store: 'blog'
        url_root: /blog
        index_tags: [ '-personal' ]

food_blog:
    class: Statocles::App::Blog
    args:
        store: 'food'
        url_root: /food

food_images:
    class: Statocles::App::Static
    args:
        store: 'food/images'
        url_root: '/food/images'

blog_images:
    class: Statocles::App::Static
    args:
        store: 'blog/images'
        url_root: '/blog/images'

talks_app:
    class: Statocles::App::Static
    args:
        store: 'talks'
        url_root: '/talks'

site:
    class: Statocles::Site
    args:
        title: preaction
        base_url: http://preaction.github.io
        theme: '::default'
        nav:
            main:
                - title: Blog
                  href: /index.html
                - title: Statocles
                  href: /Statocles
                - title: Yertl
                  href: /ETL-Yertl
                - title: Presentations
                  href: /presentations.html
                - title: Food
                  href: /food
        build_store: 'build'
        deploy: 
            $class: Statocles::Deploy::Git
            $args:
                path: '.'
        index: blog
        apps:
            blog:
                $ref: blog_app
            food:
                $ref: food_blog
            talks:
                $ref: talks_app
            food_images:
                $ref: food_images
            blog_images:
                $ref: blog_images
