theme:
    class: Statocles::Theme
    args:
        source_dir: '::default'

blog:
    class: Statocles::App::Blog
    args:
        source:
            $class: Statocles::Store
            $args:
                path: blog
        url_root: /blog
        theme:
            $ref: theme

build:
    class: Statocles::Store
    args:
        path: build

deploy:
    class: Statocles::Store
    args:
        path: .

site:
    class: Statocles::Site::Git
    args:
        title: Doug Bell
        nav:
            main:
                - title: Blog
                  href: /index.html
                - title: Presentations
                  href: /presentations.html
        build_store:
            $ref: build
        deploy_store:
            $ref: deploy
        index: blog
        apps:
            blog:
                $ref: blog
