blog_app:
    class: Statocles::App::Blog
    args:
        store: 'blog'
        url_root: /blog
        theme: '::default'
        index_tags: [ '-personal' ]

site:
    class: Statocles::Site::Git
    args:
        title: preaction
        base_url: http://preaction.github.io
        nav:
            main:
                - title: Blog
                  href: /index.html
                - title: Statocles
                  href: /Statocles
                - title: Presentations
                  href: /presentations.html
        build_store: 'build'
        deploy_store: '.'
        index: blog
        apps:
            blog:
                $ref: blog_app
