blog_app:
    class: Statocles::App::Blog
    args:
        store: 'blog'
        url_root: /blog
        index_tags: [ '-personal' ]

food_blog:
    class: Statocles::App::Blog
    args:
        store: 'food'
        url_root: /food

static_app:
    class: Statocles::App::Static
    args:
        store: '.'
        url_root: '/'

site:
    class: Statocles::Site
    args:
        title: preaction
        base_url: http://preaction.github.io
        theme: '::default'
        nav:
            main:
                - title: Blog
                  href: /index.html
                - title: Statocles
                  href: /Statocles
                - title: Yertl
                  href: /ETL-Yertl
                - title: Presentations
                  href: /presentations.html
                - title: Food
                  href: /food
        build_store: 'build'
        deploy: 
            $class: Statocles::Deploy::Git
            $args:
                path: '.'
        index: blog
        apps:
            blog:
                $ref: blog_app
            food:
                $ref: food_blog
            static:
                $ref: static_app
